#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# Enable the following to remove all files except with the pattern rm !(except_file1|except_file2)
# See also http://superuser.com/questions/231718/remove-all-files-except-for-a-few-from-a-folder-in-unix
shopt -s extglob

# Convert videos for YouTube
# See also https://bbs.archlinux.org/viewtopic.php?pid=1200542#p1200542
youtubeConvert()
{
ffmpeg -i $1 -c:v libx264 -crf 18 -preset slow -pix_fmt yuv420p -c:a copy $2.mkv
}
alias ytconvert=youtubeConvert
