#!/bin/bash

case $1 in
    battery)
		echo "Running powersaving on battery"
		
		# screen power saving"
		xbacklight -set 26.666667
    ;;
    AC)
		echo "Running powersaving on AC"
	    
		# screen power saving
		xbacklight -set 94
    ;;
esac
